fix(css): fix is-danger, is-success and is-warning state of select an…
baloise-incubator/design-system pull request #1081
Opened 2023-01-19 12:09 UTC by mladenplaninicic

…d file upload

Closes #

{{short description}}

## Acceptance Criteria

- Design Review by @Gagne87, @clastzoo
- Technical Review by @hirsch88, @mladenplaninicic, @nobilo
- [Style Guide](https://stenciljs.com/docs/style-guide) Review @hirsch88, @mladenplaninicic, @nobilo
- Visual test done by @hirsch88, @nobilo, @mladenplaninicic, @Gagne87, @clastzoo
- Functional test done by @hirsch88, @nobilo, @mladenplaninicic
- Browser Testing by @hirsch88, @nobilo, @mladenplaninicic, @Gagne87, @clastzoo
    - Desktop
        - Chrome
        - Edge
        - Safari
        - Firefox
    - Tablet
        - iPad (Landscape / Portrait)
    - Mobile
        - Safari iOS
        - Chrome Preview

2023-01-19 14:47 UTC, hirsch88 requested changes
add a patch Changeset

2023-01-19 14:47 UTC, hirsch88 commented on packages/css/scss/form/file.sass
> +        color: var(--bal-color-blue-6)
use primary instead ob blue

2023-01-19 15:20 UTC, mladenplaninicic commented on packages/css/scss/form/file.sass
> +        color: var(--bal-color-blue-6)
done

2023-01-19 16:14 UTC, hirsch88 approved these changes

2023-01-23 10:14 UTC, hirsch88 approved these changes

2023-01-23 10:14 UTC, merged