feat(bal-time-input): add new component
baloise-incubator/design-system pull request #1167
Opened 2023-02-24 08:07 UTC by JasperDeLanghe

Closes #

{{short description}}

## Acceptance Criteria

- Design Review by @Gagne87, @clastzoo
- Technical Review by @hirsch88, @mladenplaninicic
- [Style Guide](https://stenciljs.com/docs/style-guide) Review @hirsch88, @mladenplaninicic
- Visual test done by @hirsch88, @mladenplaninicic, @Gagne87, @clastzoo
- Functional test done by @hirsch88, @mladenplaninicic
- Browser Testing by @hirsch88, @mladenplaninicic, @Gagne87, @clastzoo
    - Desktop
        - Chrome
        - Edge
        - Safari
        - Firefox
    - Tablet
        - iPad (Landscape / Portrait)
    - Mobile
        - Safari iOS
        - Chrome Preview

2023-02-27 07:30 UTC, hirsch88 commented
@JasperDeLanghe would be awesome that we jump with : to the next entry part or when we enter a full hour like 20 or 06

2023-02-27 10:25 UTC, Gagne87 commented
From my point of view: 

- Placeholder should be blue-3
- Disabled state: grey-4 for input & grey-5 for placeholder

Active version is ok for me at the moment. We can improve that later on.

2023-03-02 14:33 UTC, JasperDeLanghe commented
> @JasperDeLanghe would be awesome that we jump with : to the next entry part or when we enter a full hour like 20 or 06

I finally got around to continuing work on this. @hirsch88, it should already automatically jump to the minute part when entering 2 digits in the hour part. Can you verify?

---

> From my point of view:
> 
> * Placeholder should be blue-3
> * Disabled state: grey-4 for input & grey-5 for placeholder
> 
> Active version is ok for me at the moment. We can improve that later on.

@Gagne87, since the native time input doesn't have a real "placeholder" (`--` are seen as values for the hour and minute parts) I propose the following:

- When the input is not focussed, set the text to color `blue-3`
- When the input is focused, set the text to color `primary`
- When the input has a value (both focused and not focused), set the text to color `primary`

I think this would be as close as possible to how a placeholder behaves. 
What do you think?

2023-03-03 07:04 UTC, hirsch88 commented
<img width="215" alt="image" src="https://user-images.githubusercontent.com/6384499/222653232-5b5ec59d-477b-47a3-b802-7aab54bbac73.png">

- [ ] Safari looks still weird, but google chrome is fine

2023-03-03 07:05 UTC, hirsch88 commented
@JasperDeLanghe run `npm run changeset` to create a changes with you changes described for the changelog generation.

2023-03-03 07:09 UTC, hirsch88 requested changes

2023-03-03 07:09 UTC, hirsch88 commented on packages/components/src/components/form/bal-time-input/bal-time-input.tsx
> +  getInputElement(): Promise<HTMLInputElement> {
- [ ] just put async in front of it the you can get rid off `Promise.resolve` and just return the value

2023-03-09 09:48 UTC, hirsch88 commented
- [ ] when input is disabled and invalid it is still a bit red inside

https://design-system-m9a71jt37-baloise.vercel.app/?path=/story/components-form-time-input--basic&args=invalid:true;disabled:true

2023-03-09 09:49 UTC, hirsch88 commented
- [ ] please remove the prop inverted

2023-03-09 09:56 UTC, hirsch88 requested changes

2023-03-09 09:56 UTC, hirsch88 commented on .changeset/nervous-drinks-love.md
> +bal-time-input
- [x] please add a bit more description because this will be in the changelogs for everyone

new form component bal-time-input added

2023-03-09 09:56 UTC, hirsch88 commented on packages/components/src/components/form/bal-time-input/bal-time-input.tsx
> +  @Prop() inverted = false
- [ ] Remove that one, we do no support inverted anymore

2023-03-09 09:56 UTC, hirsch88 commented on packages/components/src/components/form/bal-time-input/bal-time-input.tsx
> +  private onClick = (event: MouseEvent) => inputHandleClick(this, event)
- [ ] please remove balClick and the onClick logic. we do not support that anymore

2023-03-14 09:03 UTC, hirsch88 approved these changes

2023-03-14 09:39 UTC, merged