Fix/nav desktop
baloise-incubator/design-system pull request #327
Opened 2022-08-09 09:51 UTC by fabio-tedesco

Applies sticky behaviour, hover underlines and other small fixes/improvements for docs as well.

2022-08-09 11:25 UTC, hirsch88 requested changes

2022-08-11 07:15 UTC, hirsch88 requested changes
Fix the conflicts please

2022-08-11 10:16 UTC, madaluca commented
> Fix the conflicts please

@hirsch88 , the conflicts are fixed and the build is successful. Do you see other pain points or can this PR be merged? Thx

2022-08-11 10:27 UTC, hirsch88 approved these changes

2022-08-11 11:16 UTC, merged