chore(bal-tag): add position prop to the tag and style it in bal-card
baloise-incubator/design-system pull request #350
Opened 2022-08-12 13:31 UTC by mladenplaninicic

Closes #

{{short description}}

#### Changelog

**New**

- {{new thing}}

**Changed**

- {{change thing}}

**Removed**

- {{removed thing}}

2022-09-07 15:01 UTC, hirsch88 requested changes

2022-09-07 15:01 UTC, hirsch88 commented on packages/components/src/components.d.ts
> +        "fontWeight": Props.BalFontWeight;
- [ ] should be BalTagFontWeight

2022-09-07 15:01 UTC, hirsch88 commented on packages/components/src/components/bal-tag/bal-tag.sass
> +      font-weight: $weight-regular
- [ ] use css variable please

2022-09-07 18:21 UTC, hirsch88 commented
now I remember why we had a small size for the tables

- [x] please add the 24px size again

2022-09-09 09:34 UTC, mladenplaninicic commented
closes #317

2022-09-12 09:20 UTC, hirsch88 approved these changes

2022-09-12 12:37 UTC, merged