Feat/navigation popover
baloise-incubator/design-system pull request #408
Opened 2022-08-25 11:58 UTC by fabio-tedesco

Extend bal-navigation-popover behaviours and add two popover in stories with content examples for both the mobile and the desktop vp

2022-08-29 05:22 UTC, hirsch88 requested changes

2022-08-29 05:22 UTC, hirsch88 commented on packages/components/src/components/bal-navigation/bal-navigation.tsx
> +      this.mainNavMobile = this.el.querySelector('.bal-nav__mainmobile') as HTMLElement
- [ ] please create get method to trap the elements / avoid duplicated code

2022-08-29 05:22 UTC, hirsch88 commented on packages/components/src/components/bal-navigation/bal-navigation.tsx
> +    this.body.style.position = 'static'
- [ ] Could we create a global util function to do so.

2022-08-29 05:22 UTC, hirsch88 commented on packages/components/src/components/bal-navigation/bal-navigation.tsx
> +    this.body.style.position = 'fixed'
- [ ]  Could we create a global util function to do so.

2022-08-29 05:22 UTC, hirsch88 commented on packages/components/src/components/bal-popover/bal-popover.tsx
> +    this.body.style.position = 'static'
- [ ] use the global util function / duplicated code

2022-08-29 05:22 UTC, hirsch88 commented on packages/components/src/components/bal-popover/bal-popover.tsx
> +    this.body.style.position = 'fixed'
- [ ] use the global util function / duplicated code

2022-08-29 05:22 UTC, hirsch88 commented on packages/components/src/components/bal-popover/bal-popover.tsx
> +    /*window.scrollTo(window.scrollX, window.scrollY - 1)
- [ ] what about this commented code ?

2022-08-29 09:27 UTC, fabio-tedesco commented on packages/components/src/components/bal-popover/bal-popover.tsx
> +    /*window.scrollTo(window.scrollX, window.scrollY - 1)
deleted

2022-08-29 15:48 UTC, hirsch88 requested changes

2022-08-29 15:48 UTC, hirsch88 commented on packages/components/src/components/bal-navigation/bal-navigation.tsx
> +  getMobileNavElement(selector: string) {
- [x] no no I meant for each selector create a getter method like get mainMobileElement

2022-08-29 15:48 UTC, hirsch88 commented on packages/components/src/components/bal-navigation/bal-navigation.tsx
> +                //await this.toggleScrollingBody()
- [x] please remove comments

2022-08-29 15:48 UTC, hirsch88 commented on packages/components/src/components/bal-navigation/bal-navigation.tsx
> +                console.log('this.isMainBodyOpen BURGER ICON touch', this.isMainBodyOpen)
- [x] Remove console.logs

2022-08-31 10:15 UTC, hirsch88 approved these changes

2022-08-31 11:50 UTC, merged