fix(closable-popover): fix the click outside on popover
baloise-incubator/design-system pull request #433
Opened 2022-08-31 13:26 UTC by fabio-tedesco

**Removed**

- removed the new closable prop from the bal-popover component

2022-09-01 15:05 UTC, hirsch88 requested changes

2022-09-01 15:05 UTC, hirsch88 commented on packages/components/src/components/bal-navigation/stories/bal-navigation.stories.ts
> +        <ul class="is-flex is-flex-direction-column" style="gap: 1rem">
- [x] What is a ul and a li doing in a button

2022-09-02 08:18 UTC, fabio-tedesco commented on packages/components/src/components/bal-navigation/stories/bal-navigation.stories.ts
> +        <ul class="is-flex is-flex-direction-column" style="gap: 1rem">
hi there, they're not in a button, they're the slot content of bal-popover-content

2022-09-06 07:12 UTC, hirsch88 commented
## Acceptance Criteria

- [ ] Design Review by @Gagne87, @clastzoo
- [ ] Technical Review by @hirsch88, @mladenplaninicic, @nobilo
- Browser Testing by @hirsch88, @nobilo, @mladenplaninicic, @Gagne87, @clastzoo
    - Desktop
        - [ ] Chrome
        - [ ] Edge
        - [ ] Safari
        - [ ] Firefox
    - Tablet
        - [ ] iPad (Landscape / Portrait)
    - Mobile
        - [ ] Safari iOS
        - [ ] Chrome Preview

2022-09-06 14:30 UTC, merged

2022-09-07 09:53 UTC, Gagne87 commented
Hi @madaluca. From desktop testing following feedback: 

1. Stage seems to be behind the meta navigation -> back button not visible
2. While popup is opened it is still possible to scroll -> should not be the case!

Please compare to the attachments. Andreas will document the things that he found on VPS/VPM asap too. 

<img width="1727" alt="Screenshot 2022-09-07 at 11 46 39" src="https://user-images.githubusercontent.com/29020214/188849021-231de510-eccc-499d-af79-0ee148e3f9cb.png">

https://user-images.githubusercontent.com/29020214/188849030-b0414c0d-9953-4d9f-9718-4633665bb967.mov