Feat/animated links #358
baloise-incubator/design-system pull request #448
Opened 2022-09-02 15:16 UTC by nobilo

Closes #

{{short description}}

#### Changelog

**New**

- {{new thing}}

**Changed**

- {{change thing}}

**Removed**

- {{removed thing}}

2022-09-09 11:10 UTC, joachimprinzbach commented
closes #358

2022-09-15 14:03 UTC, nobilo commented
closes #512

2022-09-15 14:07 UTC, hirsch88 requested changes

2022-09-15 14:07 UTC, hirsch88 commented on packages/components/src/components/bal-logo/bal-logo.sass
>    position: static
- [ ] could you move the direct attributes of the block(logo) before the svg child element

2022-09-15 14:13 UTC, mladenplaninicic approved these changes

2022-09-15 14:17 UTC, hirsch88 approved these changes

2022-09-15 14:22 UTC, merged