Feat/button visual tests
baloise-incubator/design-system pull request #588
Opened 2022-09-20 19:32 UTC by joachimprinzbach

adds visual tests for button, closes #587

2022-09-20 19:55 UTC, hirsch88 requested changes

2022-09-20 19:55 UTC, hirsch88 commented on packages/components/src/components/bal-button/test/bal-button.visual.html
> +            <bal-button color="primary" color="success">Success</bal-button>
- [ ] color prop is used twice

2022-09-21 06:39 UTC, mladenplaninicic approved these changes

2022-09-21 07:11 UTC, hirsch88 approved these changes

2022-10-31 09:50 UTC, closed without merging