fix(bal-tabs): create separate numberation for o-tabs
baloise-incubator/design-system pull request #695
Opened 2022-10-06 14:45 UTC by predrag-arsic

Closes #686 

## Acceptance Criteria

- [x] Design Review by @Gagne87, @clastzoo
- [x] Technical Review by @hirsch88, @mladenplaninicic, @nobilo
- [x] [Style Guide](https://stenciljs.com/docs/style-guide) Review @hirsch88, @mladenplaninicic, @nobilo
- [x] Visual test done by @hirsch88, @nobilo, @mladenplaninicic, @Gagne87, @clastzoo
- [x] Functional test done by @hirsch88, @nobilo, @mladenplaninicic
- Browser Testing by @hirsch88, @nobilo, @mladenplaninicic, @Gagne87, @clastzoo
    - Desktop
        - [x] Chrome
        - [ ] Edge
        - [x] Safari
        - [ ] Firefox
    - Tablet
        - [ ] iPad (Landscape / Portrait)
    - Mobile
        - [ ] Safari iOS
        - [ ] Chrome Preview

2022-10-07 07:13 UTC, nobilo approved these changes

2022-10-07 09:35 UTC, mladenplaninicic commented
@predrag-arsic tnx for the contribution. I just have one small thing,  in the case when we have a failed step, we need to count that one too.

<img width="1403" alt="Screen Shot 2022-10-07 at 11 32 37" src="https://user-images.githubusercontent.com/28272339/194522454-958464c3-736d-4749-915c-94bcf9bd18da.png">

2022-10-10 07:40 UTC, hirsch88 requested changes

2022-10-10 07:40 UTC, hirsch88 commented on packages/components/src/components/bal-tabs/components/steps.tsx
> +                {tab.failed ? '!' : tab.hidden ? index : index++}
if the step is hidden then don't increase the index, but for the other status increase it 

- normal
- failed
- done

2022-10-10 08:55 UTC, mladenplaninicic approved these changes

2022-10-10 11:46 UTC, hirsch88 approved these changes

2022-10-10 12:42 UTC, merged