fix(angular-focus-directive): call setFocus method and update docs
baloise-incubator/design-system pull request #874
Opened 2022-11-14 15:00 UTC by mladenplaninicic

Closes #

{{short description}}

## Acceptance Criteria

- [ ] Design Review by @Gagne87, @clastzoo
- [ ] Technical Review by @hirsch88, @mladenplaninicic, @nobilo
- [ ] [Style Guide](https://stenciljs.com/docs/style-guide) Review @hirsch88, @mladenplaninicic, @nobilo
- [ ] Visual test done by @hirsch88, @nobilo, @mladenplaninicic, @Gagne87, @clastzoo
- [ ] Functional test done by @hirsch88, @nobilo, @mladenplaninicic
- Browser Testing by @hirsch88, @nobilo, @mladenplaninicic, @Gagne87, @clastzoo
    - Desktop
        - [ ] Chrome
        - [ ] Edge
        - [ ] Safari
        - [ ] Firefox
    - Tablet
        - [ ] iPad (Landscape / Portrait)
    - Mobile
        - [ ] Safari iOS
        - [ ] Chrome Preview

2022-11-14 15:25 UTC, nobilo approved these changes

2022-11-16 07:30 UTC, hirsch88 requested changes

2022-11-16 07:30 UTC, hirsch88 commented on cspell.json
> +    "Rebranding "
- [ ] remove the whitespace

2022-11-16 20:14 UTC, hirsch88 approved these changes

2022-11-16 20:37 UTC, merged